/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package goran.view;

import goran.controller.EventController;
import goran.controller.LocationController;
import goran.controller.TicketController;
import goran.model.Event;
import goran.model.Location;
import goran.model.Ticket;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/**
 *
 * @author Goran
 */
public class EventsPanel extends javax.swing.JPanel {

    private Event event;
    private Ticket ticket;
    private Location location;
    private EventController eventControl;
    private TicketController ticketControl;
    private LocationController locationControl;

    public EventsPanel() {

        initComponents();

        event = new Event();
        ticket = new Ticket();
        location = new Location();
        eventControl = new EventController();
        ticketControl = new TicketController();
        locationControl = new LocationController();

        updateEvents();
    }

    private void updateEvents() {

        DefaultListModel<Event> model = new DefaultListModel<>();
        lstEvents.setModel(model);
        for (Event event : eventControl.getEvents()) {
            model.addElement(event);
        }
    }

    private void updateEventTickets() {

        DefaultListModel<Ticket> model = new DefaultListModel<>();
        lstTickets.setModel(model);
        for (Ticket ticket : ticketControl.getEventTickets(event)) {
            model.addElement(ticket);
        }
    }

    private void updateLocations() {

        DefaultListModel<Location> model = new DefaultListModel<>();
        lstLocations.setModel(model);
        for (Location location : locationControl.getLocations()) {
            model.addElement(location);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frameEventsUtil = new javax.swing.JFrame();
        pnlEventsUtilMain = new javax.swing.JPanel();
        btnConfirmEvent = new javax.swing.JButton();
        btnCancelEvent = new javax.swing.JButton();
        txtEventName = new javax.swing.JTextField();
        lblErrorEvent = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        pnlEventsUtilTitle = new MotionPanel(frameEventsUtil);
        lblEventsUtil = new javax.swing.JLabel();
        frameTicketsUtil = new javax.swing.JFrame();
        pnlTicketsUtilMain = new javax.swing.JPanel();
        btnConfirmTicket = new javax.swing.JButton();
        btnCancelTicket = new javax.swing.JButton();
        txtTicketName = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtTicketPrice = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtTicketQuantity = new javax.swing.JTextField();
        lblErrorTicket = new javax.swing.JLabel();
        pnlTicketsUtilTitle = new MotionPanel(frameTicketsUtil);
        lblTicketsUtil = new javax.swing.JLabel();
        frameLocationsUtil = new javax.swing.JFrame();
        pnlLocationsUtilMain = new javax.swing.JPanel();
        btnConfirmLocation = new javax.swing.JButton();
        btnCancelLocation = new javax.swing.JButton();
        txtFindTicket = new javax.swing.JTextField();
        lblErrorLocation = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstLocations = new javax.swing.JList<>();
        pnlLocationsUtilTitle = new MotionPanel(frameLocationsUtil);
        lblLocations = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstTickets = new javax.swing.JList<>();
        btnEditEvent = new javax.swing.JButton();
        btnRemoveEvent = new javax.swing.JButton();
        btnGit = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstEvents = new javax.swing.JList<>();
        btnAddEvent = new javax.swing.JButton();
        btnAddLocation = new javax.swing.JButton();
        btnAddTicketToEvent = new javax.swing.JButton();
        btnAddTime = new javax.swing.JButton();
        lblTitle9 = new javax.swing.JLabel();
        lblTitle2 = new javax.swing.JLabel();
        btnRemoveTicket = new javax.swing.JButton();
        btnEditTicket = new javax.swing.JButton();
        lblTitle4 = new javax.swing.JLabel();
        lblEventLocation = new javax.swing.JLabel();

        frameEventsUtil.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        frameEventsUtil.setUndecorated(true);
        frameEventsUtil.setResizable(false);
        frameEventsUtil.setSize(new java.awt.Dimension(540, 190));
        frameEventsUtil.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlEventsUtilMain.setBackground(new java.awt.Color(60, 60, 70));
        pnlEventsUtilMain.setPreferredSize(new java.awt.Dimension(550, 150));
        pnlEventsUtilMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnConfirmEvent.setBackground(new java.awt.Color(0, 0, 0));
        btnConfirmEvent.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        btnConfirmEvent.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirmEvent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goran/resources/icons/btn_confirm.png"))); // NOI18N
        btnConfirmEvent.setText("POTVRDI");
        btnConfirmEvent.setBorder(null);
        btnConfirmEvent.setFocusPainted(false);
        btnConfirmEvent.setPreferredSize(new java.awt.Dimension(80, 80));
        btnConfirmEvent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmEventActionPerformed(evt);
            }
        });
        pnlEventsUtilMain.add(btnConfirmEvent, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 120, 50));

        btnCancelEvent.setBackground(new java.awt.Color(0, 0, 0));
        btnCancelEvent.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        btnCancelEvent.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelEvent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goran/resources/icons/btn_cancel.png"))); // NOI18N
        btnCancelEvent.setText("NAZAD");
        btnCancelEvent.setBorder(null);
        btnCancelEvent.setFocusPainted(false);
        btnCancelEvent.setPreferredSize(new java.awt.Dimension(80, 80));
        btnCancelEvent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelEventActionPerformed(evt);
            }
        });
        pnlEventsUtilMain.add(btnCancelEvent, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, 120, 50));

        txtEventName.setBackground(new java.awt.Color(153, 153, 153));
        txtEventName.setFont(new java.awt.Font("Lucida Sans", 0, 16)); // NOI18N
        txtEventName.setForeground(new java.awt.Color(255, 255, 255));
        pnlEventsUtilMain.add(txtEventName, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 370, 40));

        lblErrorEvent.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        lblErrorEvent.setForeground(new java.awt.Color(255, 0, 0));
        pnlEventsUtilMain.add(lblErrorEvent, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 240, 30));

        jLabel14.setFont(new java.awt.Font("Lucida Sans", 1, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("NAZIV EVENTA");
        pnlEventsUtilMain.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 130, 40));

        frameEventsUtil.getContentPane().add(pnlEventsUtilMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 540, 150));

        pnlEventsUtilTitle.setBackground(new java.awt.Color(30, 30, 40));
        pnlEventsUtilTitle.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblEventsUtil.setFont(new java.awt.Font("Lucida Sans", 1, 16)); // NOI18N
        lblEventsUtil.setForeground(new java.awt.Color(255, 255, 255));
        lblEventsUtil.setText("DODAJ NOVI EVENT");
        pnlEventsUtilTitle.add(lblEventsUtil, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 230, 40));

        frameEventsUtil.getContentPane().add(pnlEventsUtilTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 40));

        frameTicketsUtil.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        frameTicketsUtil.setUndecorated(true);
        frameTicketsUtil.setResizable(false);
        frameTicketsUtil.setSize(new java.awt.Dimension(540, 310));
        frameTicketsUtil.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlTicketsUtilMain.setBackground(new java.awt.Color(60, 60, 70));
        pnlTicketsUtilMain.setPreferredSize(new java.awt.Dimension(550, 300));
        pnlTicketsUtilMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnConfirmTicket.setBackground(new java.awt.Color(0, 0, 0));
        btnConfirmTicket.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        btnConfirmTicket.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirmTicket.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goran/resources/icons/btn_confirm.png"))); // NOI18N
        btnConfirmTicket.setText("POTVRDI");
        btnConfirmTicket.setBorder(null);
        btnConfirmTicket.setFocusPainted(false);
        btnConfirmTicket.setPreferredSize(new java.awt.Dimension(80, 80));
        btnConfirmTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmTicketActionPerformed(evt);
            }
        });
        pnlTicketsUtilMain.add(btnConfirmTicket, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 120, 50));

        btnCancelTicket.setBackground(new java.awt.Color(0, 0, 0));
        btnCancelTicket.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        btnCancelTicket.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelTicket.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goran/resources/icons/btn_cancel.png"))); // NOI18N
        btnCancelTicket.setText("NAZAD");
        btnCancelTicket.setBorder(null);
        btnCancelTicket.setFocusPainted(false);
        btnCancelTicket.setPreferredSize(new java.awt.Dimension(80, 80));
        btnCancelTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelTicketActionPerformed(evt);
            }
        });
        pnlTicketsUtilMain.add(btnCancelTicket, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, 120, 50));

        txtTicketName.setBackground(new java.awt.Color(153, 153, 153));
        txtTicketName.setFont(new java.awt.Font("Lucida Sans", 0, 16)); // NOI18N
        txtTicketName.setForeground(new java.awt.Color(255, 255, 255));
        pnlTicketsUtilMain.add(txtTicketName, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 410, 40));

        jLabel15.setFont(new java.awt.Font("Lucida Sans", 1, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("NAZIV");
        pnlTicketsUtilMain.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 90, 40));

        txtTicketPrice.setBackground(new java.awt.Color(153, 153, 153));
        txtTicketPrice.setFont(new java.awt.Font("Lucida Sans", 0, 16)); // NOI18N
        txtTicketPrice.setForeground(new java.awt.Color(255, 255, 255));
        pnlTicketsUtilMain.add(txtTicketPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 410, 40));

        jLabel16.setFont(new java.awt.Font("Lucida Sans", 1, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("CIJENA");
        pnlTicketsUtilMain.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 90, 40));

        jLabel17.setFont(new java.awt.Font("Lucida Sans", 1, 16)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("KOLIČINA");
        pnlTicketsUtilMain.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 90, 40));

        txtTicketQuantity.setBackground(new java.awt.Color(153, 153, 153));
        txtTicketQuantity.setFont(new java.awt.Font("Lucida Sans", 0, 16)); // NOI18N
        txtTicketQuantity.setForeground(new java.awt.Color(255, 255, 255));
        pnlTicketsUtilMain.add(txtTicketQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 410, 40));

        lblErrorTicket.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        lblErrorTicket.setForeground(new java.awt.Color(255, 0, 0));
        pnlTicketsUtilMain.add(lblErrorTicket, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 240, 50));

        frameTicketsUtil.getContentPane().add(pnlTicketsUtilMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 540, 270));

        pnlTicketsUtilTitle.setBackground(new java.awt.Color(30, 30, 40));
        pnlTicketsUtilTitle.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTicketsUtil.setFont(new java.awt.Font("Lucida Sans", 1, 16)); // NOI18N
        lblTicketsUtil.setForeground(new java.awt.Color(255, 255, 255));
        lblTicketsUtil.setText("DODAJ NOVU ULAZNICU");
        pnlTicketsUtilTitle.add(lblTicketsUtil, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 230, 40));

        frameTicketsUtil.getContentPane().add(pnlTicketsUtilTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 40));

        frameLocationsUtil.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        frameLocationsUtil.setUndecorated(true);
        frameLocationsUtil.setResizable(false);
        frameLocationsUtil.setSize(new java.awt.Dimension(420, 470));
        frameLocationsUtil.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlLocationsUtilMain.setBackground(new java.awt.Color(60, 60, 70));
        pnlLocationsUtilMain.setPreferredSize(new java.awt.Dimension(550, 180));
        pnlLocationsUtilMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnConfirmLocation.setBackground(new java.awt.Color(0, 0, 0));
        btnConfirmLocation.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        btnConfirmLocation.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirmLocation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goran/resources/icons/btn_confirm.png"))); // NOI18N
        btnConfirmLocation.setText("POTVRDI");
        btnConfirmLocation.setBorder(null);
        btnConfirmLocation.setFocusPainted(false);
        btnConfirmLocation.setPreferredSize(new java.awt.Dimension(80, 80));
        btnConfirmLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmLocationActionPerformed(evt);
            }
        });
        pnlLocationsUtilMain.add(btnConfirmLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 120, 50));

        btnCancelLocation.setBackground(new java.awt.Color(0, 0, 0));
        btnCancelLocation.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        btnCancelLocation.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelLocation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goran/resources/icons/btn_cancel.png"))); // NOI18N
        btnCancelLocation.setText("NAZAD");
        btnCancelLocation.setBorder(null);
        btnCancelLocation.setFocusPainted(false);
        btnCancelLocation.setPreferredSize(new java.awt.Dimension(80, 80));
        btnCancelLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelLocationActionPerformed(evt);
            }
        });
        pnlLocationsUtilMain.add(btnCancelLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 120, 50));

        txtFindTicket.setBackground(new java.awt.Color(153, 153, 153));
        txtFindTicket.setFont(new java.awt.Font("Lucida Sans", 0, 16)); // NOI18N
        txtFindTicket.setForeground(new java.awt.Color(255, 255, 255));
        pnlLocationsUtilMain.add(txtFindTicket, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 380, 40));

        lblErrorLocation.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        lblErrorLocation.setForeground(new java.awt.Color(255, 0, 0));
        pnlLocationsUtilMain.add(lblErrorLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 120, 50));

        lstLocations.setBackground(new java.awt.Color(153, 153, 153));
        lstLocations.setFont(new java.awt.Font("Lucida Sans", 0, 16)); // NOI18N
        lstLocations.setForeground(new java.awt.Color(255, 255, 255));
        lstLocations.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstLocationsValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(lstLocations);

        pnlLocationsUtilMain.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 380, 260));

        frameLocationsUtil.getContentPane().add(pnlLocationsUtilMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 420, 430));

        pnlLocationsUtilTitle.setBackground(new java.awt.Color(30, 30, 40));
        pnlLocationsUtilTitle.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLocations.setFont(new java.awt.Font("Lucida Sans", 1, 16)); // NOI18N
        lblLocations.setForeground(new java.awt.Color(255, 255, 255));
        lblLocations.setText("ODABERI LOKACIJU");
        pnlLocationsUtilTitle.add(lblLocations, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 230, 40));

        frameLocationsUtil.getContentPane().add(pnlLocationsUtilTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 40));

        setBackground(new java.awt.Color(60, 60, 70));
        setPreferredSize(new java.awt.Dimension(880, 620));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lstTickets.setBackground(new java.awt.Color(153, 153, 153));
        lstTickets.setFont(new java.awt.Font("Lucida Sans", 0, 16)); // NOI18N
        lstTickets.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(lstTickets);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 360, 470, 170));

        btnEditEvent.setBackground(new java.awt.Color(0, 0, 0));
        btnEditEvent.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        btnEditEvent.setForeground(new java.awt.Color(255, 255, 255));
        btnEditEvent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goran/resources/icons/btn_edit.png"))); // NOI18N
        btnEditEvent.setText("UREDI");
        btnEditEvent.setBorder(null);
        btnEditEvent.setFocusPainted(false);
        btnEditEvent.setPreferredSize(new java.awt.Dimension(80, 80));
        btnEditEvent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditEventActionPerformed(evt);
            }
        });
        add(btnEditEvent, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 550, 100, 50));

        btnRemoveEvent.setBackground(new java.awt.Color(0, 0, 0));
        btnRemoveEvent.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        btnRemoveEvent.setForeground(new java.awt.Color(255, 255, 255));
        btnRemoveEvent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goran/resources/icons/btn_remove.png"))); // NOI18N
        btnRemoveEvent.setText("UKLONI");
        btnRemoveEvent.setBorder(null);
        btnRemoveEvent.setFocusPainted(false);
        btnRemoveEvent.setPreferredSize(new java.awt.Dimension(80, 80));
        btnRemoveEvent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveEventActionPerformed(evt);
            }
        });
        add(btnRemoveEvent, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 550, 100, 50));

        btnGit.setBackground(new java.awt.Color(0, 0, 0));
        btnGit.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        btnGit.setForeground(new java.awt.Color(255, 255, 255));
        btnGit.setText("GITHUB");
        btnGit.setBorder(null);
        btnGit.setFocusPainted(false);
        btnGit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGit.setPreferredSize(new java.awt.Dimension(80, 80));
        btnGit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGitActionPerformed(evt);
            }
        });
        add(btnGit, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 550, 140, 50));

        lstEvents.setBackground(new java.awt.Color(153, 153, 153));
        lstEvents.setFont(new java.awt.Font("Lucida Sans", 0, 16)); // NOI18N
        lstEvents.setForeground(new java.awt.Color(255, 255, 255));
        lstEvents.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstEventsValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(lstEvents);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 320, 500));

        btnAddEvent.setBackground(new java.awt.Color(0, 0, 0));
        btnAddEvent.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        btnAddEvent.setForeground(new java.awt.Color(255, 255, 255));
        btnAddEvent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goran/resources/icons/btn_add.png"))); // NOI18N
        btnAddEvent.setText("DODAJ");
        btnAddEvent.setBorder(null);
        btnAddEvent.setFocusPainted(false);
        btnAddEvent.setPreferredSize(new java.awt.Dimension(80, 80));
        btnAddEvent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddEventActionPerformed(evt);
            }
        });
        add(btnAddEvent, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, 100, 50));

        btnAddLocation.setBackground(new java.awt.Color(0, 0, 0));
        btnAddLocation.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        btnAddLocation.setForeground(new java.awt.Color(255, 255, 255));
        btnAddLocation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goran/resources/icons/btn_location.png"))); // NOI18N
        btnAddLocation.setBorder(null);
        btnAddLocation.setFocusPainted(false);
        btnAddLocation.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAddLocation.setPreferredSize(new java.awt.Dimension(80, 80));
        btnAddLocation.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAddLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddLocationActionPerformed(evt);
            }
        });
        add(btnAddLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, 50, 50));

        btnAddTicketToEvent.setBackground(new java.awt.Color(0, 0, 0));
        btnAddTicketToEvent.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        btnAddTicketToEvent.setForeground(new java.awt.Color(255, 255, 255));
        btnAddTicketToEvent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goran/resources/icons/btn_add.png"))); // NOI18N
        btnAddTicketToEvent.setText("DODAJ");
        btnAddTicketToEvent.setBorder(null);
        btnAddTicketToEvent.setFocusPainted(false);
        btnAddTicketToEvent.setPreferredSize(new java.awt.Dimension(80, 80));
        btnAddTicketToEvent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTicketToEventActionPerformed(evt);
            }
        });
        add(btnAddTicketToEvent, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 550, 100, 50));

        btnAddTime.setBackground(new java.awt.Color(0, 0, 0));
        btnAddTime.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        btnAddTime.setForeground(new java.awt.Color(255, 255, 255));
        btnAddTime.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goran/resources/icons/btn_calendar.png"))); // NOI18N
        btnAddTime.setBorder(null);
        btnAddTime.setFocusPainted(false);
        btnAddTime.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAddTime.setPreferredSize(new java.awt.Dimension(80, 80));
        btnAddTime.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        add(btnAddTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 50, 50));

        lblTitle9.setFont(new java.awt.Font("Lucida Sans", 1, 16)); // NOI18N
        lblTitle9.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle9.setText("DODAJ VRIJEME EVENTA");
        add(lblTitle9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 420, 50));

        lblTitle2.setFont(new java.awt.Font("Lucida Sans", 1, 16)); // NOI18N
        lblTitle2.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle2.setText("KALENDAR - PLACEHOLDER");
        lblTitle2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(lblTitle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, 470, 170));

        btnRemoveTicket.setBackground(new java.awt.Color(0, 0, 0));
        btnRemoveTicket.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        btnRemoveTicket.setForeground(new java.awt.Color(255, 255, 255));
        btnRemoveTicket.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goran/resources/icons/btn_remove.png"))); // NOI18N
        btnRemoveTicket.setText("UKLONI");
        btnRemoveTicket.setBorder(null);
        btnRemoveTicket.setFocusPainted(false);
        btnRemoveTicket.setPreferredSize(new java.awt.Dimension(80, 80));
        btnRemoveTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveTicketActionPerformed(evt);
            }
        });
        add(btnRemoveTicket, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 550, 100, 50));

        btnEditTicket.setBackground(new java.awt.Color(0, 0, 0));
        btnEditTicket.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        btnEditTicket.setForeground(new java.awt.Color(255, 255, 255));
        btnEditTicket.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goran/resources/icons/btn_edit.png"))); // NOI18N
        btnEditTicket.setText("UREDI");
        btnEditTicket.setBorder(null);
        btnEditTicket.setFocusPainted(false);
        btnEditTicket.setPreferredSize(new java.awt.Dimension(80, 80));
        btnEditTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditTicketActionPerformed(evt);
            }
        });
        add(btnEditTicket, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 550, 100, 50));

        lblTitle4.setFont(new java.awt.Font("Lucida Sans", 1, 16)); // NOI18N
        lblTitle4.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle4.setText("RASPOLOŽIVE ULAZNICE");
        add(lblTitle4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 320, 370, 40));

        lblEventLocation.setFont(new java.awt.Font("Lucida Sans", 1, 16)); // NOI18N
        lblEventLocation.setForeground(new java.awt.Color(255, 255, 255));
        lblEventLocation.setText("DODAJ LOKACIJU EVENTA");
        add(lblEventLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, 410, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditEventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditEventActionPerformed

        try {

            lblEventsUtil.setText(Utils.EDIT_EVENT);
            txtEventName.setText(event.getName());
            frameEventsUtil.setVisible(true);
            frameEventsUtil.setLocationRelativeTo(this);

        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnEditEventActionPerformed

    private void btnRemoveEventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveEventActionPerformed

        if (lstEvents.getSelectedIndex() == -1) {

        } else {

            try {

                ticketControl.removeEventTickets(event);
                updateEventTickets();

            } catch (Exception e) {
            }

            eventControl.removeEvent(event);
            updateEvents();

        }
    }//GEN-LAST:event_btnRemoveEventActionPerformed

    private void btnAddLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddLocationActionPerformed

        if (lstEvents.getSelectedIndex() == -1) {

        } else {

            updateLocations();
            lblErrorLocation.setText("");
            frameLocationsUtil.setVisible(true);
            frameLocationsUtil.setLocationRelativeTo(this);
        }
    }//GEN-LAST:event_btnAddLocationActionPerformed

    private void btnConfirmEventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmEventActionPerformed

        if (txtEventName.getText().matches("")) {

            lblErrorEvent.setText(Utils.INPUT_ERROR);

        } else {

            event.setName(txtEventName.getText());

            if (lblEventsUtil.getText().matches(Utils.ADD_EVENT)) {

                eventControl.addEvent(event);

            } else if (lblEventsUtil.getText().matches(Utils.EDIT_EVENT)) {

                eventControl.editEvent(event);
            }

            updateEvents();
            lblErrorEvent.setText("");
            frameEventsUtil.dispose();
        }
    }//GEN-LAST:event_btnConfirmEventActionPerformed

    private void btnCancelEventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelEventActionPerformed

        frameEventsUtil.dispose();
    }//GEN-LAST:event_btnCancelEventActionPerformed

    private void btnGitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGitActionPerformed

        try {
            Runtime.getRuntime().exec("cmd /c start https://github.com/gkovac42/event-manager-edunova");
        } catch (IOException ex) {
            Logger.getLogger(EventsPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnGitActionPerformed

    private void lstEventsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstEventsValueChanged

        try {

            event = lstEvents.getSelectedValue();
            updateEventTickets();
            lblEventLocation.setText(eventControl.getEventLocation(event));

        } catch (NullPointerException e) {
            lblEventLocation.setText("DODAJ LOKACIJU EVENTA");
        }
    }//GEN-LAST:event_lstEventsValueChanged

    private void btnConfirmTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmTicketActionPerformed

        if (txtTicketName.getText().matches("") || txtTicketPrice.getText().matches("")) {

            lblErrorTicket.setText(Utils.INPUT_ERROR);

        } else {

            ticket.setName(txtTicketName.getText());
            ticket.setPrice(Double.parseDouble(txtTicketPrice.getText()));
            ticket.setEvent(lstEvents.getSelectedValue().getId());

            if (lblTicketsUtil.getText().matches(Utils.ADD_TICKET)) {
                ticketControl.addTicket(ticket);

            } else if (lblTicketsUtil.getText().matches(Utils.EDIT_TICKET)) {
                ticketControl.editTicket(ticket);
            }

            updateEventTickets();
            frameTicketsUtil.dispose();
        }
    }//GEN-LAST:event_btnConfirmTicketActionPerformed

    private void btnCancelTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelTicketActionPerformed

        frameTicketsUtil.dispose();
    }//GEN-LAST:event_btnCancelTicketActionPerformed

    private void btnAddTicketToEventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTicketToEventActionPerformed

        if (lstEvents.getSelectedIndex() == -1) {

        } else {

            lblTicketsUtil.setText(Utils.ADD_TICKET);
            lblErrorTicket.setText("");
            txtTicketName.setText(event.getName());
            txtTicketPrice.setText("");

            frameTicketsUtil.setVisible(true);
            frameTicketsUtil.setLocationRelativeTo(this);
        }
    }//GEN-LAST:event_btnAddTicketToEventActionPerformed

    private void btnAddEventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddEventActionPerformed

        lblEventsUtil.setText(Utils.ADD_EVENT);
        lblErrorEvent.setText("");
        txtEventName.setText("");

        frameEventsUtil.setVisible(true);
        frameEventsUtil.setLocationRelativeTo(this);
    }//GEN-LAST:event_btnAddEventActionPerformed

    private void btnRemoveTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveTicketActionPerformed

        try {

            ticket = lstTickets.getSelectedValue();
            ticketControl.removeTicket(ticket);
            updateEventTickets();

        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnRemoveTicketActionPerformed

    private void btnEditTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditTicketActionPerformed

        try {

            ticket = lstTickets.getSelectedValue();
            lblTicketsUtil.setText(Utils.EDIT_TICKET);
            txtTicketName.setText(ticket.getName());
            txtTicketPrice.setText(ticket.getPrice().toString());
            frameTicketsUtil.setVisible(true);
            frameTicketsUtil.setLocationRelativeTo(this);

        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnEditTicketActionPerformed

    private void btnConfirmLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmLocationActionPerformed

        if (lstLocations.getSelectedIndex() == -1) {
            lblErrorLocation.setText(Utils.EVENT_SELECTION_ERROR);
        } else {

            eventControl.setEventLocation(event, location);
            lblEventLocation.setText(location.toString());
            frameLocationsUtil.dispose();

        }


    }//GEN-LAST:event_btnConfirmLocationActionPerformed

    private void btnCancelLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelLocationActionPerformed

        frameLocationsUtil.dispose();
    }//GEN-LAST:event_btnCancelLocationActionPerformed

    private void lstLocationsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstLocationsValueChanged

        try {

            location = lstLocations.getSelectedValue();

        } catch (Exception e) {
        }
    }//GEN-LAST:event_lstLocationsValueChanged

    public void applyTheme() {

        //Events Panel
        setBackground(Theme.color2);
        btnAddEvent.setBackground(Theme.color3);
        btnRemoveEvent.setBackground(Theme.color3);
        btnEditEvent.setBackground(Theme.color3);
        btnGit.setBackground(Theme.color3);
        btnAddLocation.setBackground(Theme.color3);
        btnAddTime.setBackground(Theme.color3);
        btnAddTicketToEvent.setBackground(Theme.color3);
        btnRemoveTicket.setBackground(Theme.color3);
        btnEditTicket.setBackground(Theme.color3);
        lstEvents.setBackground(Theme.color4);
        lstEvents.setForeground(Theme.font1);
        lstTickets.setBackground(Theme.color4);
        lstTickets.setForeground(Theme.font1);

        //Events Util
        pnlEventsUtilTitle.setBackground(Theme.color1);
        pnlEventsUtilMain.setBackground(Theme.color2);
        btnConfirmEvent.setBackground(Theme.color3);
        btnCancelEvent.setBackground(Theme.color3);
        txtEventName.setBackground(Theme.color4);
        txtEventName.setForeground(Theme.font1);

        //Locations util
        pnlLocationsUtilTitle.setBackground(Theme.color1);
        pnlLocationsUtilMain.setBackground(Theme.color2);
        btnConfirmLocation.setBackground(Theme.color3);
        btnCancelLocation.setBackground(Theme.color3);
        lstLocations.setBackground(Theme.color4);
        lstLocations.setForeground(Theme.font1);

        //Tickets Util
        pnlTicketsUtilTitle.setBackground(Theme.color1);
        pnlTicketsUtilMain.setBackground(Theme.color2);
        btnConfirmTicket.setBackground(Theme.color3);
        btnCancelTicket.setBackground(Theme.color3);
        txtTicketName.setBackground(Theme.color4);
        txtTicketPrice.setBackground(Theme.color4);
        txtTicketQuantity.setBackground(Theme.color4);
        txtTicketName.setForeground(Theme.font1);
        txtTicketPrice.setForeground(Theme.font1);
        txtTicketQuantity.setForeground(Theme.font1);
        txtFindTicket.setBackground(Theme.color4);
        txtFindTicket.setForeground(Theme.font1);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddEvent;
    private javax.swing.JButton btnAddLocation;
    private javax.swing.JButton btnAddTicketToEvent;
    private javax.swing.JButton btnAddTime;
    private javax.swing.JButton btnCancelEvent;
    private javax.swing.JButton btnCancelLocation;
    private javax.swing.JButton btnCancelTicket;
    private javax.swing.JButton btnConfirmEvent;
    private javax.swing.JButton btnConfirmLocation;
    private javax.swing.JButton btnConfirmTicket;
    private javax.swing.JButton btnEditEvent;
    private javax.swing.JButton btnEditTicket;
    private javax.swing.JButton btnGit;
    private javax.swing.JButton btnRemoveEvent;
    private javax.swing.JButton btnRemoveTicket;
    private javax.swing.JFrame frameEventsUtil;
    private javax.swing.JFrame frameLocationsUtil;
    private javax.swing.JFrame frameTicketsUtil;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblErrorEvent;
    private javax.swing.JLabel lblErrorLocation;
    private javax.swing.JLabel lblErrorTicket;
    private javax.swing.JLabel lblEventLocation;
    private javax.swing.JLabel lblEventsUtil;
    private javax.swing.JLabel lblLocations;
    private javax.swing.JLabel lblTicketsUtil;
    private javax.swing.JLabel lblTitle2;
    private javax.swing.JLabel lblTitle4;
    private javax.swing.JLabel lblTitle9;
    private javax.swing.JList<Event> lstEvents;
    private javax.swing.JList<Location> lstLocations;
    private javax.swing.JList<Ticket> lstTickets;
    private javax.swing.JPanel pnlEventsUtilMain;
    private javax.swing.JPanel pnlEventsUtilTitle;
    private javax.swing.JPanel pnlLocationsUtilMain;
    private javax.swing.JPanel pnlLocationsUtilTitle;
    private javax.swing.JPanel pnlTicketsUtilMain;
    private javax.swing.JPanel pnlTicketsUtilTitle;
    private javax.swing.JTextField txtEventName;
    private javax.swing.JTextField txtFindTicket;
    private javax.swing.JTextField txtTicketName;
    private javax.swing.JTextField txtTicketPrice;
    private javax.swing.JTextField txtTicketQuantity;
    // End of variables declaration//GEN-END:variables
}
