/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package goran.view;

import goran.util.Theme;
import goran.util.TxtUtil;
import goran.controller.GoogleMapsController;
import goran.controller.HibernateController;
import goran.controller.InputController;
import goran.model.Location;
import javax.swing.DefaultListModel;
import javax.swing.border.EtchedBorder;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author Goran
 */
public class LocationsPanel extends javax.swing.JPanel {

    private Location location;
    private HibernateController<Location> ctrlLocation;
    private GoogleMapsController mapControl;

    private String sortLocations;
    private static final int MAP_ZOOM = 16;
    private static final String MAP_TYPE = "L";

    public LocationsPanel() {

        initComponents();

        location = new Location();
        ctrlLocation = new HibernateController<>();
        mapControl = new GoogleMapsController();
        sortLocations = "name";
        
        lstLocations.setComponentPopupMenu(locationsMenu);
        menuButtonGroup.setSelected(mnuNam.getModel(), true);
        
        addLocationSearchListener();

        updateLocations(sortLocations);
    }

    private void updateLocations(String orderBy) {

        DefaultListModel<Location> model = new DefaultListModel<>();
        lstLocations.setModel(model);
        for (Location l : ctrlLocation.getOrderedList(location, orderBy)) {
            model.addElement(l);
        }
    }

    private void clearUserInput() {
        txtLocationName.setText("");
        txtLocationAddress.setText("");
        txtLocationLocality.setText("");
        txtLocationCountry.setText("");
        lblError.setText("");
        lblMap.setIcon(null);
    }

    private void getUserInput() {
        location.setName(txtLocationName.getText());
        location.setAddress(txtLocationAddress.getText());
        location.setLocality(txtLocationLocality.getText());
        location.setCountry(txtLocationCountry.getText());
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        locationsMenu = new javax.swing.JPopupMenu();
        mnuNam = new javax.swing.JRadioButtonMenuItem();
        mnuLocality = new javax.swing.JRadioButtonMenuItem();
        mnuDateCreated = new javax.swing.JRadioButtonMenuItem();
        menuButtonGroup = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstLocations = new javax.swing.JList<>();
        txtLocationName = new javax.swing.JTextField();
        txtLocationAddress = new javax.swing.JTextField();
        txtLocationLocality = new javax.swing.JTextField();
        txtLocationCountry = new javax.swing.JTextField();
        btnFindOnMap = new javax.swing.JButton();
        btnEditLocation = new javax.swing.JButton();
        btnRemoveLocation = new javax.swing.JButton();
        btnNewLocation = new javax.swing.JButton();
        lblMap = new javax.swing.JLabel();
        lblTitle1 = new javax.swing.JLabel();
        lblTitle2 = new javax.swing.JLabel();
        lblError = new javax.swing.JLabel();
        lblTitle6 = new javax.swing.JLabel();
        txtFindLocation = new javax.swing.JTextField();
        lblTitle5 = new javax.swing.JLabel();
        lblSearch2 = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();

        locationsMenu.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        locationsMenu.setToolTipText("");

        menuButtonGroup.add(mnuNam);
        mnuNam.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        mnuNam.setText("Po nazivu");
        mnuNam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuNamActionPerformed(evt);
            }
        });
        locationsMenu.add(mnuNam);

        menuButtonGroup.add(mnuLocality);
        mnuLocality.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        mnuLocality.setText("Po mjestu");
        mnuLocality.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuLocalityActionPerformed(evt);
            }
        });
        locationsMenu.add(mnuLocality);

        menuButtonGroup.add(mnuDateCreated);
        mnuDateCreated.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        mnuDateCreated.setSelected(true);
        mnuDateCreated.setText("Po unosu");
        mnuDateCreated.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDateCreatedActionPerformed(evt);
            }
        });
        locationsMenu.add(mnuDateCreated);

        setBackground(new java.awt.Color(60, 60, 70));
        setMinimumSize(new java.awt.Dimension(700, 500));
        setPreferredSize(new java.awt.Dimension(700, 500));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lstLocations.setBackground(new java.awt.Color(120, 120, 120));
        lstLocations.setFont(new java.awt.Font("Lucida Sans", 0, 15)); // NOI18N
        lstLocations.setForeground(new java.awt.Color(255, 255, 255));
        lstLocations.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstLocations.setFocusable(false);
        lstLocations.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstLocationsValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(lstLocations);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 320, 180));

        txtLocationName.setBackground(new java.awt.Color(120, 120, 120));
        txtLocationName.setFont(new java.awt.Font("Lucida Sans", 0, 15)); // NOI18N
        txtLocationName.setForeground(new java.awt.Color(255, 255, 255));
        txtLocationName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindOnMapActionPerformed(evt);
            }
        });
        add(txtLocationName, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 240, 40));

        txtLocationAddress.setBackground(new java.awt.Color(120, 120, 120));
        txtLocationAddress.setFont(new java.awt.Font("Lucida Sans", 0, 15)); // NOI18N
        txtLocationAddress.setForeground(new java.awt.Color(255, 255, 255));
        txtLocationAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindOnMapActionPerformed(evt);
            }
        });
        add(txtLocationAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, 240, 40));

        txtLocationLocality.setBackground(new java.awt.Color(120, 120, 120));
        txtLocationLocality.setFont(new java.awt.Font("Lucida Sans", 0, 15)); // NOI18N
        txtLocationLocality.setForeground(new java.awt.Color(255, 255, 255));
        txtLocationLocality.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindOnMapActionPerformed(evt);
            }
        });
        add(txtLocationLocality, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 240, 40));

        txtLocationCountry.setBackground(new java.awt.Color(120, 120, 120));
        txtLocationCountry.setFont(new java.awt.Font("Lucida Sans", 0, 15)); // NOI18N
        txtLocationCountry.setForeground(new java.awt.Color(255, 255, 255));
        txtLocationCountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindOnMapActionPerformed(evt);
            }
        });
        add(txtLocationCountry, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 450, 240, 40));

        btnFindOnMap.setBackground(new java.awt.Color(0, 0, 0));
        btnFindOnMap.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        btnFindOnMap.setForeground(new java.awt.Color(255, 255, 255));
        btnFindOnMap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goran/resources/icons/btn_locate.png"))); // NOI18N
        btnFindOnMap.setText("PRONAĐI NA KARTI");
        btnFindOnMap.setBorder(null);
        btnFindOnMap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindOnMapActionPerformed(evt);
            }
        });
        add(btnFindOnMap, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 450, 350, 40));

        btnEditLocation.setBackground(new java.awt.Color(0, 0, 0));
        btnEditLocation.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        btnEditLocation.setForeground(new java.awt.Color(255, 255, 255));
        btnEditLocation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goran/resources/icons/btn_save.png"))); // NOI18N
        btnEditLocation.setText("SPREMI");
        btnEditLocation.setBorder(null);
        btnEditLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditLocationActionPerformed(evt);
            }
        });
        add(btnEditLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 100, 40));

        btnRemoveLocation.setBackground(new java.awt.Color(0, 0, 0));
        btnRemoveLocation.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        btnRemoveLocation.setForeground(new java.awt.Color(255, 255, 255));
        btnRemoveLocation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goran/resources/icons/btn_cancel_order.png"))); // NOI18N
        btnRemoveLocation.setText("UKLONI");
        btnRemoveLocation.setBorder(null);
        btnRemoveLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveLocationActionPerformed(evt);
            }
        });
        add(btnRemoveLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 100, 40));

        btnNewLocation.setBackground(new java.awt.Color(0, 0, 0));
        btnNewLocation.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        btnNewLocation.setForeground(new java.awt.Color(255, 255, 255));
        btnNewLocation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goran/resources/icons/btn_new.png"))); // NOI18N
        btnNewLocation.setText("NOVA");
        btnNewLocation.setBorder(null);
        btnNewLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewLocationActionPerformed(evt);
            }
        });
        add(btnNewLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 100, 40));

        lblMap.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.gray, java.awt.Color.darkGray));
        lblMap.setPreferredSize(new java.awt.Dimension(460, 460));
        add(lblMap, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 350, 430));

        lblTitle1.setFont(new java.awt.Font("Lucida Sans", 1, 15)); // NOI18N
        lblTitle1.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle1.setText("ADRESA");
        add(lblTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 70, 40));

        lblTitle2.setFont(new java.awt.Font("Lucida Sans", 1, 15)); // NOI18N
        lblTitle2.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle2.setText("MJESTO");
        add(lblTitle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 70, 40));

        lblError.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        lblError.setForeground(new java.awt.Color(255, 0, 0));
        lblError.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        add(lblError, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 240, 40));

        lblTitle6.setFont(new java.awt.Font("Lucida Sans", 1, 15)); // NOI18N
        lblTitle6.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle6.setText("DRŽAVA");
        add(lblTitle6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 70, 40));

        txtFindLocation.setBackground(new java.awt.Color(120, 120, 120));
        txtFindLocation.setFont(new java.awt.Font("Lucida Sans", 0, 15)); // NOI18N
        txtFindLocation.setForeground(new java.awt.Color(255, 255, 255));
        add(txtFindLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 280, 40));

        lblTitle5.setFont(new java.awt.Font("Lucida Sans", 1, 15)); // NOI18N
        lblTitle5.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle5.setText("NAZIV");
        add(lblTitle5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 70, 40));

        lblSearch2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSearch2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goran/resources/icons/btn_search.png"))); // NOI18N
        add(lblSearch2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 40, 40));

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goran/resources/icons/bg_main.jpg"))); // NOI18N
        lblBackground.setOpaque(true);
        add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 500));
    }// </editor-fold>//GEN-END:initComponents

    private void lstLocationsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstLocationsValueChanged

        if (lstLocations.getSelectedIndex() == -1) {
        } else {

            location = lstLocations.getSelectedValue();

            txtLocationAddress.setText(location.getAddress());
            txtLocationLocality.setText(location.getLocality());
            txtLocationCountry.setText(location.getCountry());
            txtLocationName.setText(location.getName());

            mapControl.openOrDownloadMap(location, MAP_ZOOM, lblMap, MAP_TYPE);

            lblError.setText("");
        }


    }//GEN-LAST:event_lstLocationsValueChanged

    private void btnFindOnMapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindOnMapActionPerformed

        try {

            getUserInput();

            String[] mapData = mapControl.getGoogleMapsData(mapControl.generateUrl(location));

            location.setLat(mapData[0]);
            location.setLng(mapData[1]);

            mapControl.openOrDownloadMap(location, MAP_ZOOM, lblMap, "L");

            txtLocationAddress.setText(mapData[3] + " " + mapData[2]);
            txtLocationLocality.setText(mapData[4]);
            txtLocationCountry.setText(mapData[5]);

        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnFindOnMapActionPerformed

    private void btnEditLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditLocationActionPerformed

        if (location == null) {
            lblError.setText("Odaberite postojeću ili kreirajte novu lokaciju");
        } else {

            getUserInput();

            if (InputController.locationInputError(location)) {

                lblError.setText(TxtUtil.INPUT_ERROR);

            } else {

                ctrlLocation.save(location);
                updateLocations(sortLocations);
                lblError.setText("");
                location = new Location();
            }
        }
    }//GEN-LAST:event_btnEditLocationActionPerformed

    private void btnRemoveLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveLocationActionPerformed

        if (lstLocations.getSelectedIndex() == -1) {
        } else {

            clearUserInput();
            ctrlLocation.delete(location);
            updateLocations(sortLocations);
            location = new Location();

        }
    }//GEN-LAST:event_btnRemoveLocationActionPerformed

    private void btnNewLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewLocationActionPerformed

        clearUserInput();
        lstLocations.setSelectedIndex(-1);
        location = new Location();
    }//GEN-LAST:event_btnNewLocationActionPerformed

    private void mnuLocalityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuLocalityActionPerformed
        sortLocations = "locality";
        updateLocations(sortLocations);
    }//GEN-LAST:event_mnuLocalityActionPerformed

    private void mnuNamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuNamActionPerformed
        sortLocations = "name";
        updateLocations(sortLocations);
    }//GEN-LAST:event_mnuNamActionPerformed

    private void mnuDateCreatedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDateCreatedActionPerformed
        sortLocations = "dateCreated";
        updateLocations(sortLocations);
    }//GEN-LAST:event_mnuDateCreatedActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditLocation;
    private javax.swing.JButton btnFindOnMap;
    private javax.swing.JButton btnNewLocation;
    private javax.swing.JButton btnRemoveLocation;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblMap;
    private javax.swing.JLabel lblSearch2;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JLabel lblTitle2;
    private javax.swing.JLabel lblTitle5;
    private javax.swing.JLabel lblTitle6;
    private javax.swing.JPopupMenu locationsMenu;
    private javax.swing.JList<Location> lstLocations;
    private javax.swing.ButtonGroup menuButtonGroup;
    private javax.swing.JRadioButtonMenuItem mnuDateCreated;
    private javax.swing.JRadioButtonMenuItem mnuLocality;
    private javax.swing.JRadioButtonMenuItem mnuNam;
    private javax.swing.JTextField txtFindLocation;
    private javax.swing.JTextField txtLocationAddress;
    private javax.swing.JTextField txtLocationCountry;
    private javax.swing.JTextField txtLocationLocality;
    private javax.swing.JTextField txtLocationName;
    // End of variables declaration//GEN-END:variables

    private void addLocationSearchListener() {

        txtFindLocation.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                DefaultListModel<Location> model = new DefaultListModel<>();
                lstLocations.setModel(model);
                for (Location location : ctrlLocation.find(location, sortLocations, txtFindLocation.getText())) {
                    model.addElement(location);
                }
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                DefaultListModel<Location> model = new DefaultListModel<>();
                lstLocations.setModel(model);
                for (Location location : ctrlLocation.find(location, sortLocations, txtFindLocation.getText())) {
                    model.addElement(location);
                }
            }

            @Override
            public void changedUpdate(DocumentEvent e) {

            }
        });
    }

    public void applyTheme() {

        setBackground(Theme.color2);
        btnEditLocation.setBackground(Theme.color3);
        btnRemoveLocation.setBackground(Theme.color3);
        btnNewLocation.setBackground(Theme.color3);
        btnFindOnMap.setBackground(Theme.color3);
        txtLocationName.setBackground(Theme.color4);
        txtLocationAddress.setBackground(Theme.color4);
        txtLocationLocality.setBackground(Theme.color4);
        txtLocationCountry.setBackground(Theme.color4);
        txtLocationName.setForeground(Theme.font1);
        txtLocationAddress.setForeground(Theme.font1);
        txtLocationLocality.setForeground(Theme.font1);
        txtLocationCountry.setForeground(Theme.font1);
        txtFindLocation.setBackground(Theme.color4);
        txtFindLocation.setForeground(Theme.font1);
        lstLocations.setBackground(Theme.color4);
        lstLocations.setForeground(Theme.font1);
        lblMap.setBorder(new EtchedBorder(Theme.color1, Theme.color2));

    }
}
