/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package goran.view;

import goran.controller.TicketController;
import goran.model.Ticket;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Goran
 */
public class TicketsPanel extends javax.swing.JPanel {

    private Ticket ticket;
    private TicketController ticketControl;

    /**
     * Creates new form TicketsPanel
     */
    public TicketsPanel() {
        initComponents();
        ticketControl = new TicketController();
        updateTickets();
    }

    public void updateTickets() {

        DefaultTableModel model = (DefaultTableModel) tblTickets.getModel();
        model.setRowCount(0);
        Object rowData[] = new Object[3];

        for (Ticket ticket : ticketControl.getTickets()) {
            rowData[0] = ticket.getName();
            rowData[1] = ticket.getPrice();
            rowData[2] = ticket.getEvent();
            model.addRow(rowData);
        }
    }

    public void findTickets() {

        DefaultTableModel model = (DefaultTableModel) tblTickets.getModel();
        model.setRowCount(0);
        Object rowData[] = new Object[3];

        for (Ticket ticket : ticketControl.findTickets(txtFindTickets.getText())) {
            rowData[0] = ticket.getName();
            rowData[1] = ticket.getPrice();
            rowData[2] = ticket.getEvent();
            model.addRow(rowData);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        tblTickets = new javax.swing.JTable();
        txtFindTickets = new javax.swing.JTextField();
        btnFindTickets = new javax.swing.JButton();

        setBackground(new java.awt.Color(60, 60, 70));
        setMinimumSize(new java.awt.Dimension(700, 500));
        setPreferredSize(new java.awt.Dimension(700, 500));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblTickets.setBackground(new java.awt.Color(120, 120, 120));
        tblTickets.getTableHeader().setFont(new java.awt.Font("Lucida Sans", 1, 16));
        tblTickets.setFont(new java.awt.Font("Lucida Sans", 0, 16)); // NOI18N
        tblTickets.setForeground(new java.awt.Color(255, 255, 255));
        tblTickets.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NAZIV", "CIJENA", "KOLIČINA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTickets.setRowHeight(24);
        tblTickets.getColumnModel().getColumn(0).setPreferredWidth(250);
        tblTickets.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        jScrollPane3.setViewportView(tblTickets);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 680, 430));

        txtFindTickets.setBackground(new java.awt.Color(120, 120, 120));
        txtFindTickets.setFont(new java.awt.Font("Lucida Sans", 0, 16)); // NOI18N
        txtFindTickets.setForeground(new java.awt.Color(255, 255, 255));
        add(txtFindTickets, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 570, 40));

        btnFindTickets.setBackground(new java.awt.Color(0, 0, 0));
        btnFindTickets.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        btnFindTickets.setForeground(new java.awt.Color(255, 255, 255));
        btnFindTickets.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goran/resources/icons/btn_search.png"))); // NOI18N
        btnFindTickets.setText("TRAŽI");
        btnFindTickets.setBorder(null);
        btnFindTickets.setFocusPainted(false);
        btnFindTickets.setPreferredSize(new java.awt.Dimension(80, 80));
        btnFindTickets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindTicketsActionPerformed(evt);
            }
        });
        add(btnFindTickets, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 10, 100, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void btnFindTicketsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindTicketsActionPerformed
        
        if (txtFindTickets.getText().matches("")) {
            updateTickets();
        } else {
            findTickets();
        }
    }//GEN-LAST:event_btnFindTicketsActionPerformed

    public void applyTheme() {

        setBackground(Theme.color2);
        btnFindTickets.setBackground(Theme.color3);
        txtFindTickets.setBackground(Theme.color4);
        tblTickets.setBackground(Theme.color4);
        tblTickets.setForeground(Theme.font1);
        txtFindTickets.setForeground(Theme.font1);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFindTickets;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblTickets;
    private javax.swing.JTextField txtFindTickets;
    // End of variables declaration//GEN-END:variables
}
